apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - registerArtifact
  registerArtifact:
    steps:
      - with:
          action-name: kcp1
          version: "1.0"
          url: docker.io/myapp/myimg:1.0.0
        run: ""
        uses: cloudbees-io/register-build-artifact@v2
        name: ""
        env: {}
        shell: ""
  appr:
    needs: build
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 84aeae94-fed3-11ec-9441-42010a83ae7a
      notifyAllEligibleUsers: false
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
